import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import fs from "node:fs";
import path from "node:path";

const proxyTarget = process.env.VITE_PROXY_TARGET ?? "http://127.0.0.1:4000";

/**
 * Optionally load a locally-trusted dev cert generated by mkcert
 * (https://github.com/FiloSottile/mkcert). Required for iOS Safari camera
 * access (navigator.mediaDevices needs a secure context).
 *
 * Generate certs from this directory:
 *   mkcert localhost 10.1.10.9 127.0.0.1
 *
 * mkcert outputs files like:
 *   localhost+2.pem        (cert)
 *   localhost+2-key.pem    (key)
 *
 * If both files are present, Vite serves over HTTPS. Otherwise falls back to HTTP.
 */
function loadDevHttpsConfig(): { key: Buffer; cert: Buffer } | undefined {
  const dir = path.resolve(__dirname);
  const candidates = fs.readdirSync(dir).filter((f) => /^localhost.*\.pem$/.test(f));
  const certFile = candidates.find((f) => !f.includes("-key."));
  const keyFile = candidates.find((f) => f.includes("-key."));
  if (!certFile || !keyFile) return undefined;
  try {
    return {
      key: fs.readFileSync(path.join(dir, keyFile)),
      cert: fs.readFileSync(path.join(dir, certFile)),
    };
  } catch {
    return undefined;
  }
}

const httpsConfig = loadDevHttpsConfig();

/**
 * Dev: proxy API routes to Liquor Kings Express (same-origin cookies when deployed).
 * Override: VITE_PROXY_TARGET=http://127.0.0.1:4000 npm run dev
 */
export default defineConfig({
  base: "/scanner/",
  plugins: [react()],
  server: {
    port: 5174,
    host: "0.0.0.0",
    https: httpsConfig,
    allowedHosts: [".ngrok-free.dev", ".ngrok.io", ".ngrok-free.app", "localhost", "10.1.10.9"],
    // Every API prefix the scanner calls is proxied to VITE_PROXY_TARGET so
    // `npm run dev:scanner` works fully against ANY backend. Point it at prod
    // to iterate the UI instantly (Vite hot reload) with zero deploys:
    //   VITE_PROXY_TARGET=https://liquor-kings.fly.dev npm run dev:scanner
    // (Supabase auth talks to supabase.co directly, so it's not proxied here.)
    proxy: Object.fromEntries(
      [
        "/operator-review",
        "/price-book",
        "/cart",
        "/inventory",
        "/execution-runs",
        "/catalog",
        "/home",
        "/orders",
        "/order-templates",
        "/assistant",
        "/tags",
        "/auth",
      ].map((prefix) => [prefix, { target: proxyTarget, changeOrigin: true }]),
    ),
  },
});
